### ISSUE TITLE
Basic attacks during battle

### ISSUE THREAD

**Issue by Dar13** [Dar13/scifi-tactics#3]
Implementation of the `Attack` phase with a couple of basic starting attacks to allow fleshing out the systems.

Ideas for starting attacks:
 * Melee, range of 1
 * Ranged, direct LoS (aka gun)
 * Ranged AoE, no LoS needed (hacking attack, etc)

### Tasks

- [x] 'Attack' tiles that show up when selecting attack target
- [x] Selection menu for weapons
- [ ] Target validity verification, based on weapon type (sometimes attacking the ground is ok)
